name: 🚚 Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: Jontes-Tech
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Checkout
       uses: actions/checkout@v2
     - name: Build and push Docker image
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ghcr.io/Jontes-Tech/ensas:latest